### ISSUE TITLE
rmg not listed in Divvun Manager

### ISSUE THREAD

**Issue by Trondtr** [giellalt/lang-rmg#1]
In the list of languages in Divvun Manager, rmg (Traveller Norwegian) is missing. The reason is probably that the lang-rmg repository is fairly new.

The fix will thus be to add it to the DM.

**Comment by Trondtr** [comment]
rmg is now added, and works.

**Comment by snomos** [comment]
Fixed via https://github.com/divvun/divvun-manager-windows/issues/43.
